# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_image.andreaseliassen.com	FALSE	/	FALSE	0	__RequestVerificationToken	uon0pA44-YOqv5zB2_ZMLxGEENWZmmm97VgdUs_20ERtwJd0bpowqpB8XJSYLF1TYVOoMKjP1qLTSVejKjzA4qdVC1BVJBb_ugS9rEJgZTU1
